class Names:
    username = "username"
    name = "name"
    family = "family"
    password = "password"
    create_at = "create_at"
    update_at = "update_at"
    role = "role"
    image="image"
    men_sex='men_sex'
    Email="Email"
    token="token"
    role_user = "user"
    role_admin = "admin"
    money= "money"
